
path: ''E:\\Code Repository\\Campus\\Big Data Analytics\\Final Project\\YOLO\\repository\\data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: vehicle registration plate
  1: vehicle